### ISSUE TITLE
Update for 10.0.7 and beyond

### ISSUE THREAD

**Issue by b-morgan** [syndenbock/AddonProfiles#1]
This addon is very useful but it needs to be kept up to date. Checking "Load out of date AddOns" is not the best solution when Blizzard is in "You are running a new version of the game..." mode.

I am an addon author so I know it only takes a few minutes to update the .toc file(s) and release.

**Comment by syndenbock** [comment]
I actually forgot to update the interface version of this addon when 10.0.7 was released but I did so now and released a new version.
